# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-PB8TzSgqRDsuKbQ0iBGMgFXKlnJ43w6

##تمرین سوم
"""

import numpy as np
import matplotlib.pyplot as plt

x=np.linspace(-5,5,500)
f1 = x**3
f2 = np.cos(1.2 * x)
f3 = np.exp(-x**2)

plt.plot(x, f1, linestyle='--')
plt.fill_between(x, f1, color='skyblue', alpha=0.5)
plt.xlabel('x')
plt.ylabel('f(x)')
plt.title('plot of x^3')
plt.legend()
plt.show()

plt.plot(x,f2,linestyle="--",color='green')
plt.plot(x,f3,color='red')
plt.title('plot of mathmatical functions')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.legend()
plt.grid(True)
plt.show

