# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/193_xp16VYksGZf3v6O90fUc4bzcSwsD8

تمرین چهارم
"""

import numpy as np
import matplotlib.pyplot as plt

def plot_normal_dist(n_points, mean, std_dev):
    data = np.random.normal(loc=mean, scale=std_dev, size=n_points)

    plt.figure(figsize=(8, 5))
    plt.hist(data, bins=100, density=True, color='skyblue', edgecolor='black', alpha=0.6)

    x = np.linspace(mean - 4*std_dev, mean + 4*std_dev, 1000)
    y = (1 / (std_dev * np.sqrt(2 * np.pi))) * np.exp(-0.5 * ((x - mean) / std_dev)**2)
    plt.plot(x, y, color='red', label='Normal PDF')

    plt.title(f'Normal Distribution (n={n_points}, mean={mean}, std={std_dev})')
    plt.xlabel('Value')
    plt.ylabel('Density')
    plt.legend()
    plt.grid(True)
    plt.show()


plot_normal_dist(10, 0, 1)
plot_normal_dist(1000, 0, 1)
plot_normal_dist(100000, 0, 1)

